import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/libs/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex text-sm")}>
        <nav className="p-2 border-r border-sand-600-light dark:border-sand-600-dark h-screen">
          Nav
        </nav>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
